[package]
name = "bedalyze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bedalyze"
crate-type = ["cdylib"]

[dependencies]
flate2 = "1.1.2"
pyo3 = "0.25.0"
